language: node_js
node_js: stable
before_install:
  - "curl -L https://install.meteor.com/ | /bin/sh"
  - java -version
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g gulp