language: node_js

node_js:
  - stable

sudo: required

before_install:
  - "curl -L https://install.meteor.com/ | /bin/sh"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm start &
  - sleep 100
  - npm test